try:
    print('tried')
except Exception as e:
    print(e)
finally:
    print('finally...')
